### ISSUE TITLE
Multiple statuses with the same `context` value

### ISSUE THREAD

**Issue by benedfit** [Sibz/wait-for-github-status-action#17]
I have a scenario where the API returns multiple statuses with the same `context` value, one has `state: pending` and another have `state: success`. In this instance, I never receive a success state and always getting `pending` from `outputs.failedCheckStates`

**Comment by Sibz** [comment]
Sorry for the delay in responding to your issue. I am unable to work on this at the moment, have you had any luck in figuring out the issue? I would welcome any collaboration to address the underlying issue you are experiencing.
